main: de.mschramm.neverdie.NeverDiePlugin
name: NeverDiePlugin
version: 0.1
api-version: 1.16

commands:
  lifes:
    description: Get your remaining lifes
    usage: /<command>
  startneverdie:
    description: Start the Never Die Game
    usage: /<command> <seed> <spawnX> <spawnZ>
    permission: neverdie.start

permissions:
  neverdie.start:
    description: Permission to start the neverdie modus
    default: op
